name: python-deployment

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.8'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage flake8 pytest
          pip install -r src/requirements.txt

      - name: Lint with flake8
        run: |
          flake8 src/ --show-source --statistics
        continue-on-error: true
        
      - name: Check code complexity with flake8
        run: |
          flake8 src/ --exit-zero --max-complexity=10 --statistics
        continue-on-error: true
      
      - name: Test with pytest
        run: |
          pytest src --ds=src.settings --pythonpath=src --maxfail=1 --disable-warnings
      
      - name: Run coverage tests
        run: |
          coverage run src/manage.py test
          coverage report
      
      - name: Show coverage report
        run: |
          coverage report
          coverage html
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: src/htmlcov

      - name: Upload Python code as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-code
          path: src/
